### Send POST request with json body
POST http://localhost:4000/authentication/register
Content-Type: application/json

{
  "forename": "",
  "surname": "",
  "username": "georg",
  "email": "georg",
  "password": "georg",
  "passkey": ""
}

### Send POST request with json body
DELETE http://localhost:4000/authentication/delete
Content-Type: application/json

{
  "identifier": "georg"
}

### Send POST request with json body
POST http://localhost:4000/authentication/login
Content-Type: application/json

{
  "credentials": ["georg", "georg"]
}

###
POST http://localhost:4000/authentication/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxLCJzZXNzaW9uSWQiOjE2LCJyZWZyZXNoIjp0cnVlLCJpYXQiOjE2NTc1Mzg0MTcsImV4cCI6MTY1NzUzODUzN30.32cmQ9dsEmq4yNB25BXX_7sIGraHC5MfvbW2riMUb08

{

}
