### register
POST http://localhost:4000/authentication/register
Content-Type: application/json

{
  "forename": "",
  "surname": "",
  "username": "georg",
  "email": "georg",
  "password": "georg",
  "passkey": ""
}

### delete
DELETE http://localhost:4000/authentication/delete
Content-Type: application/json

{
  "identifier": "georg"
}

### login
POST http://localhost:4000/authentication/login
Content-Type: application/json

{
  "credentials": [
    "georg",
    "georg"
  ]
}

### refresh
POST http://localhost:4000/authentication/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxLCJzZXNzaW9uSWQiOjE3LCJyZWZyZXNoIjp0cnVlLCJpYXQiOjE2NTc1NDA0MTEsImV4cCI6MTY1NzU0MDUzMX0.0NUHMbcVmRvubuGkpkU_H6c9zBpdGHdK03ZQ7fytyGU

{
}

### logout
POST http://localhost:4000/authentication/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxLCJzZXNzaW9uSWQiOjE3LCJyZWZyZXNoIjp0cnVlLCJpYXQiOjE2NTc1NDA0MTEsImV4cCI6MTY1NzU0MDUzMX0.0NUHMbcVmRvubuGkpkU_H6c9zBpdGHdK03ZQ7fytyGU

{
}


