### register
POST http://localhost:4000/authentication/register
Content-Type: application/json

{
  "forename": "",
  "surname": "",
  "username": "georg",
  "email": "georg",
  "password": "georg",
  "passkey": ""
}

### delete
DELETE http://localhost:4000/authentication/delete
Content-Type: application/json

{
  "identifier": "georg"
}

### login
POST http://localhost:4000/authentication/login
Content-Type: application/json

{
  "credentials": [
    "georg",
    "georg"
  ]
}

### refresh
POST http://localhost:4000/authentication/refresh
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxLCJzZXNzaW9uSWQiOjUwLCJjYW5SZWZyZXNoIjp0cnVlLCJpYXQiOjE2NTc1NTgwOTgsImV4cCI6MTY1NzU1ODk5OH0.BBnP32kb3JQzYtK1z7XXjkfDrc0Zbn4zmk66gY2TUN0

{
}

### logout
POST http://localhost:4000/authentication/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZ2VudElkIjoxLCJzZXNzaW9uSWQiOjQ4LCJjYW5SZWZyZXNoIjp0cnVlLCJpYXQiOjE2NTc1NTU3MTMsImV4cCI6MTY1NzU1NjYxM30.RrtuF3qLr1H_WOZnRPHoQxCa1_ENco2Fkv0nOeXINZY

{
}


